apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-apps: qiyuesuo-jvm
  name: qiyuesuo-jvm
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: jvm-port
  namespaceSelector:
    matchNames:
    - qiyuesuo
  selector:
    matchLabels:
      prometheus-metrics: jvm
